// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql1

import (
	"context"

	"github.com/Warashi/compgen/complexitytest/gql1/model"
)

type Stub struct {
	QueryResolver struct {
		Foo func(ctx context.Context, a *int, b *int, c *int) (*model.FooConnection, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Foo(ctx context.Context, a *int, b *int, c *int) (*model.FooConnection, error) {
	return r.QueryResolver.Foo(ctx, a, b, c)
}
