// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql1

import (
	"context"

	"github.com/Warashi/compgen/complexitytest/calculation/gql1/model"
)

type Stub struct {
	QueryResolver struct {
		Foo  func(ctx context.Context, a *int, b int, c *int) (*model.FooConnection, error)
		Bar  func(ctx context.Context, a *int, b int, c *int) (*model.FooConnection, error)
		Baz  func(ctx context.Context, ids []string) (*model.FooConnection, error)
		Bazz func(ctx context.Context, ids []string) (*model.FooConnection, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Foo(ctx context.Context, a *int, b int, c *int) (*model.FooConnection, error) {
	return r.QueryResolver.Foo(ctx, a, b, c)
}
func (r *stubQuery) Bar(ctx context.Context, a *int, b int, c *int) (*model.FooConnection, error) {
	return r.QueryResolver.Bar(ctx, a, b, c)
}
func (r *stubQuery) Baz(ctx context.Context, ids []string) (*model.FooConnection, error) {
	return r.QueryResolver.Baz(ctx, ids)
}
func (r *stubQuery) Bazz(ctx context.Context, ids []string) (*model.FooConnection, error) {
	return r.QueryResolver.Bazz(ctx, ids)
}
