// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql0

import (
	"context"

	"github.com/Warashi/compgen/complexitytest/gql0/model"
)

type Stub struct {
	QueryResolver struct {
		Foo func(ctx context.Context, after *string, first *int, before *string, last *int) (*model.FooConnection, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Foo(ctx context.Context, after *string, first *int, before *string, last *int) (*model.FooConnection, error) {
	return r.QueryResolver.Foo(ctx, after, first, before, last)
}
