// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Foo struct {
	Bar string `json:"bar"`
}

type FooConnection struct {
	Edges    []*FooEdge `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type FooEdge struct {
	Cursor string `json:"cursor"`
	Node   *Foo   `json:"node"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}
